version: '3'
services:
  client:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: board_frontend
    ports:
      - "3000:80"
    volumes:
      - "./app/node_modules"
      - "./:/app"
